---
title: "Assignment 4"
author: "Rohith Desamseety"
date: "2022-11-02"
output: pdf_document
---
```{r}
library(readr)
Pharmaceuticals_RD <- read.csv("~/Downloads/Pharmaceuticals (1).csv")
View(Pharmaceuticals_RD)
```

```{r}
library(ggplot2)
library(factoextra)
library(flexclust)
library(cluster)
library(tidyverse)
summary(Pharmaceuticals_RD)

#Task 1
#Use only the numerical variables (1 to 9) to cluster the 21 firms. Justify the various choices made in conducting the cluster analysis, such as weights for different variables, the specific clustering algorithm(s) used, the number of clusters formed, and so on. 
R <- na.omit(Pharmaceuticals_RD)
R
row.names <- R[,1]
Pharmaceuticals1 <-  R[,3:11]
head(Pharmaceuticals1)
Pharmaceuticals2 <- scale(Pharmaceuticals1)
head(Pharmaceuticals2)
fviz_nbclust(Pharmaceuticals2, kmeans, method = "wss") +labs(subtitle = "Elbow Method")
fviz_nbclust(Pharmaceuticals2, kmeans, method = "silhouette") + labs(subtitle = "Silhouette Method")
fviz_nbclust(Pharmaceuticals2, kmeans, method = "gap_stat") + labs(subtitle = "Gap Stat Method")
```
```{r}
set.seed(64060)
k5 <- kmeans(Pharmaceuticals2, centers = 5, nstart = 25)
k5 $centers
fviz_cluster(k5, data = Pharmaceuticals2)
k5
Distance <- dist(Pharmaceuticals2, method = "euclidian")
fviz_dist(Distance)
Fitting <- kmeans(Pharmaceuticals2,5)
aggregate(Pharmaceuticals2,by = list(Fitting$cluster), FUN = mean)
Pharmaceuticals3 <- data.frame(Pharmaceuticals2,Fitting$cluster)
Pharmaceuticals3
library(cluster)
clusplot(Pharmaceuticals2,Fitting$cluster, color = TRUE, shade = TRUE, 
         labels = 2,
         lines = 0)
```


```{r}
#Task 2
#Interpret the clusters with respect to the numerical variables used in forming the clusters.

aggregate(Pharmaceuticals2, by = list(Fitting$cluster), FUN = mean)
Pharmacy <- data.frame(Pharmaceuticals2,k5$cluster)
Pharmacy
#CLuster 1:- JNJ, MRK, GSK, PFE
#Cluster 1: Highest Market_Cap and lowest Beta/PE Ratio
#Cluster 2:- AHM, WPI, AVE
#Cluster 2: Highest Revenue Growth and lowest PE/Asset Turnover Ratio
#Cluster 3:- CHTT, IVX, MRX, ELN
#Cluster 3: Highest Beta/leverage/Asset Turnover Ratio and lowest 
#Net_Profit_Margin, PE ratio and Marke#Cluster
#Cluster 4:- AGN,BAY, PHA
#Cluster 4: Highest PE ratio and lowest Leverage/Asset_Turnover
#Cluster 5:- ABT, WYE, AZN, SGP, BMY, NVS, LLY
#Cluster 5: Highest Net_Proft_Margin and lowest Leverage
```


```{r}
#Task3
#Is there a pattern in the clusters with respect to the numerical variables (10 to 12)? #(those not used in forming the clusters)

RD <- Pharmaceuticals_RD[12:14] %>% mutate(Clusters=k5$cluster)
ggplot(RD, mapping = aes(factor(Clusters), fill =Median_Recommendation))+geom_bar(position='dodge')+labs(x ='Clusters')
ggplot(RD, mapping = aes(factor(Clusters),fill = Location))+geom_bar(position = 'dodge')+labs(x ='Clusters')
ggplot(RD, mapping = aes(factor(Clusters),fill = Exchange))+geom_bar(position = 'dodge')+labs(x ='Clusters')
#The above graphs indicate that there is a slim pattern in the clusters.
#Although the cluster 1 has a different Hold and Moderate Buy median, a different count from the US and Germany, and a different country count, the firms are evenly divided among AMEX,NASDAQ and NYSE.
#The cluster 2 is only listed on the NYSE, has equal Hold and Moderate Buy medians, and is evenly divided across the US and Canada.
#The Cluster 3 is listed on the NYSE and has equal Moderate Buy and Sell medians as well as a separate count from France, Ireland, and the US.
#The Hold median in Cluster 4 is the highest, followed by Moderate Buy, Strong Buy, and Hold medians. They come from the US, the UK, and Switzerland, and they are listed on the NYSE.
#The Cluster 5 is scattered throughout the US and the UK, has the same hold and moderate buy medians, and is likewise listed on the NYSE.
```


```{r}
#TASK 4
#Provide an appropriate name for each cluster using any or all of the variables in the dataset. 

#Cluster 1 :- Buy Cluster
#Cluster 2 :- Sceptical Cluster
#Cluster 3 :- Moderate Buy Cluster
#Cluster 4 :- Hold Cluster
#Cluster 5 :- High Hold Cluster 
```
